version: '3'
services:
  app:
    build:
      context: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - local
    container_name: server_app_1
    mem_limit: 512m
  db:
    image: postgres:latest
    env_file:
      - .env
    environment:
      POSTGRES_DB: gfg_db
      POSTGRES_USER: Ferius
      POSTGRES_PASSWORD: Ferius1901
    networks:
      - local

networks:
  local:
  prod: